<a href="https://colab.research.google.com/github/pgordin/OptDisc2025/blob/main/Grafy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importowanie pakietów

In [1]:
import numpy as np
from random import random, seed

# Funkcje grafowe

In [2]:
def print_matrix(vertices, matrix):
  """
  Wypisuje na ekranie graf podany jako macierz sąsiedztwa
  """
  n = len(matrix)
  if (vertices is not None) and (len(vertices) == n):
    vv = vertices
  else:
    vv = range(1, n+1)
  for i in range(n):
    print(vv[i], ":", end="")
    for j in range(n):
      if matrix[i, j]:
        print(" ", vv[j], end="")
    print("")

In [3]:
def print_graph(graph):
  """
  Wypisuje na ekranie graf podany jako lista sąsiedztwa (słownik pythona)
  """
  for v in graph:
    print(v, ":", end="")
    for u in graph[v]:
      print(" ", u, end="")
    print("")

## Modyfikacje grafów

In [10]:
def add_vertex(graph, vertex):
  """
  Nowy wierzchołek do istniejącego grafu
  """
  if vertex not in graph:
    graph[vertex] = []


def add_arc(graph, arc):
  """
  Nowy łuk (podany jako para wierzchołków) do istniejącego grafu.
  Rozważamy grafy proste, skierowane
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)


def add_edge(graph, edge):
  """
  Nowa krawędź (podana jako para wierzchołków) do istniejącego grafu.
  Rozważamy grafy proste, nieskierowane, (bez pętli)
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Pętla!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)


## Wczytywanie i zapis do plików.

In [11]:
def graph_from_edges(filename, directed = 0):
  """
  Wczytuje graf z pliku tekstowego, gdzie podany jest opis krawędzi (dwa słowa)
  lub wierzchołka (jedno słowo).
  Wynik podany jest w formie słownika (grafu).
  Zmienna filename zawiera pełną ścieżkę do pliku.
  """
  graph = {}
  with open(filename, "r") as file:    # otwarcie pliku do odczytu
    for line in file:
      words = line.strip().split()  # podział linii na słowa
      if len(words) == 1:           # jedno słowo - opis wierzchołka
        add_vertex(graph, words[0])
      elif len(words) >= 2:         # dwa słowa - krawędź lub łuk
        if directed:
          add_arc(graph, (words[0], words[1]))
        else:
          add_edge(graph, (words[0], words[1]))
  return graph


In [14]:
def graph_to_neighbourlist(graph, filename):
  """
  Zapisuje graf (jako słownik) do pliku tekstowego w formie listy sąsiedztwa.
  """
  with open(filename, "w") as file:
    for v in graph:
      line = f"{v}:"
      for u in graph[v]:
        line += f" {u}"
      line += "\n"
      file.write(line)

# Przykłady wykorzystania

## Wczytywanie plików

In [7]:
%%writefile edges.txt
a b
a c
b d
c e
f


Writing edges.txt


In [8]:
%cat edges.txt

a b
a c
b d
c e
f


In [12]:
graf1 = graph_from_edges("edges.txt")
print_graph(graf1)

a :  b  c
b :  a  d
c :  a  e
d :  b
e :  c
f :


In [13]:
graf2 = graph_from_edges("edges.txt", directed=1)
print_graph(graf2)

a :  b  c
b :  d
c :  e
d :
e :
f :


In [15]:
graph_to_neighbourlist(graf1, "lista1.txt")
graph_to_neighbourlist(graf2, "lista2.txt")

In [16]:
%cat lista1.txt

a: b c
b: a d
c: a e
d: b
e: c
f:


In [17]:
%cat lista2.txt

a: b c
b: d
c: e
d:
e:
f:


## Pierwsze zajęcia

In [ ]:
vertices = ["a", "b", "c", "d", "e"]
matrix = np.array([[0,1,1,0,0],[1,0,1,1,0],[1,1,0,0,1],[1,1,0,0,0],[0,1,0,0,0]])
print(vertices)
print(matrix)
print("-----------------------------")
print_matrix(vertices, matrix)
print("-----------------------------")
print_matrix(None, matrix)

['a', 'b', 'c', 'd', 'e']
[[0 1 1 0 0]
 [1 0 1 1 0]
 [1 1 0 0 1]
 [1 1 0 0 0]
 [0 1 0 0 0]]
-----------------------------
a :  b  c
b :  a  c  d
c :  a  b  e
d :  a  b
e :  b
-----------------------------
1 :  2  3
2 :  1  3  4
3 :  1  2  5
4 :  1  2
5 :  2


In [ ]:
graph = {
    'a': ['b', 'c'],
    'b': ['a', 'c', 'd'],
    'c': ['a', 'b', 'e'],
    'd': ['a', 'b'],
    'e': ['b']
}
print(graph)

{'a': ['b', 'c'], 'b': ['a', 'c', 'd'], 'c': ['a', 'b', 'e'], 'd': ['a', 'b'], 'e': ['b']}


In [ ]:
print_graph(graph)

a :  b  c
b :  a  c  d
c :  a  b  e
d :  a  b
e :  b


In [ ]:
add_vertex(graph, 'f')
print_graph(graph)

a :  b  c
b :  a  c  d
c :  a  b  e
d :  a  b
e :  b
f :


In [ ]:
add_edge(graph, ('a', 'f'))
print_graph(graph)

a :  b  c  f
b :  a  c  d
c :  a  b  e
d :  a  b
e :  b
f :  a


In [ ]:
add_edge(graph, ('c', 'e'))
add_edge(graph, ('e', 'b'))
print_graph(graph)

a :  b  c  f
b :  a  c  d  e
c :  a  b  e
d :  a  b
e :  b  c
f :  a


In [ ]:
add_edge(graph, ('c', 'c'))

ValueError: Pętla!

In [ ]:
add_arc(graph, ('c', 'c'))
print_graph(graph)

a :  b  c  f
b :  a  c  d  e
c :  a  b  e  c
d :  a  b
e :  b  c
f :  a


# Tworzenie grafów losowych $G(n,p)$.

In [ ]:
# dla powtarzalności
np.random.seed(2025)

In [ ]:
# losujemy graf G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if np.random.random() < p:
      add_edge(random_graph, (i, j))

In [ ]:
print_graph(random_graph)

1 :  2  7  9
2 :  1  9
3 :  4  6  8  9
4 :  3  7
5 :  6  7
6 :  3  5  8
7 :  1  4  5  9
8 :  3  6  9
9 :  1  2  3  7  8
10 :
