<a href="https://colab.research.google.com/github/pgordin/OptDisc2025/blob/main/Grafy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importowanie pakietów

In [1]:
import numpy as np
from random import random, seed

# Funkcje grafowe

In [2]:
def print_matrix(vertices, matrix):
  """
  Wypisuje na ekranie graf podany jako macierz sąsiedztwa
  """
  n = len(matrix)
  if (vertices is not None) and (len(vertices) == n):
    vv = vertices
  else:
    vv = range(1, n+1)
  for i in range(n):
    print(vv[i], ":", end="")
    for j in range(n):
      if matrix[i, j]:
        print(" ", vv[j], end="")
    print("")

In [6]:
def print_graph(graph):
  """
  Wypisuje na ekranie graf podany jako lista sąsiedztwa (słownik pythona)
  """
  for v in graph:
    print(v, ":", end="")
    for u in graph[v]:
      print(" ", u, end="")
    print("")

## Modyfikacje grafów

In [8]:
def add_vertex(graph, vertex):
  """
  Nowy wierzchołek do istniejącego grafu
  """
  if vertex not in graph:
    graph[vertex] = []


def add_arc(graph, arc):
  """
  Nowy łuk (podany jako para wierzchołków) do istniejącego grafu.
  Rozważamy grafy proste, skierowane
  """
  u, v = arc
  add_vertex(graph, u)
  add_vertex(graph, v)
  if v not in graph[u]:
    graph[u].append(v)


def add_edge(graph, edge):
  """
  Nowa krawędź (podana jako para wierzchołków) do istniejącego grafu.
  Rozważamy grafy proste, nieskierowane, (bez pętli)
  """
  u, v = edge
  add_vertex(graph, u)
  add_vertex(graph, v)
  if u == v:
    raise ValueError("Pętla!")
  if v not in graph[u]:
    graph[u].append(v)
  if u not in graph[v]:
    graph[v].append(u)


# Przykłady wykorzystania

In [3]:
vertices = ["a", "b", "c", "d", "e"]
matrix = np.array([[0,1,1,0,0],[1,0,1,1,0],[1,1,0,0,1],[1,1,0,0,0],[0,1,0,0,0]])
print(vertices)
print(matrix)
print("-----------------------------")
print_matrix(vertices, matrix)
print("-----------------------------")
print_matrix(None, matrix)

['a', 'b', 'c', 'd', 'e']
[[0 1 1 0 0]
 [1 0 1 1 0]
 [1 1 0 0 1]
 [1 1 0 0 0]
 [0 1 0 0 0]]
-----------------------------
a :  b  c
b :  a  c  d
c :  a  b  e
d :  a  b
e :  b
-----------------------------
1 :  2  3
2 :  1  3  4
3 :  1  2  5
4 :  1  2
5 :  2


In [5]:
graph = {
    'a': ['b', 'c'],
    'b': ['a', 'c', 'd'],
    'c': ['a', 'b', 'e'],
    'd': ['a', 'b'],
    'e': ['b']
}
print(graph)

{'a': ['b', 'c'], 'b': ['a', 'c', 'd'], 'c': ['a', 'b', 'e'], 'd': ['a', 'b'], 'e': ['b']}


In [7]:
print_graph(graph)

a :  b  c
b :  a  c  d
c :  a  b  e
d :  a  b
e :  b


In [9]:
add_vertex(graph, 'f')
print_graph(graph)

a :  b  c
b :  a  c  d
c :  a  b  e
d :  a  b
e :  b
f :


In [11]:
add_edge(graph, ('a', 'f'))
print_graph(graph)

a :  b  c  f
b :  a  c  d
c :  a  b  e
d :  a  b
e :  b
f :  a


In [12]:
add_edge(graph, ('c', 'e'))
add_edge(graph, ('e', 'b'))
print_graph(graph)

a :  b  c  f
b :  a  c  d  e
c :  a  b  e
d :  a  b
e :  b  c
f :  a


In [13]:
add_edge(graph, ('c', 'c'))

ValueError: Pętla!

In [14]:
add_arc(graph, ('c', 'c'))
print_graph(graph)

a :  b  c  f
b :  a  c  d  e
c :  a  b  e  c
d :  a  b
e :  b  c
f :  a


# Tworzenie grafów losowych $G(n,p)$.

In [21]:
# dla powtarzalności
np.random.seed(2025)

In [22]:
# losujemy graf G(10, 1/3)
n = 10
p = 1/3
random_graph = {}
for i in range(1, n+1):
  add_vertex(random_graph, i)
  for j in range(1, i):
    if np.random.random() < p:
      add_edge(random_graph, (i, j))

In [23]:
print_graph(random_graph)

1 :  2  7  9
2 :  1  9
3 :  4  6  8  9
4 :  3  7
5 :  6  7
6 :  3  5  8
7 :  1  4  5  9
8 :  3  6  9
9 :  1  2  3  7  8
10 :
